In [15]:
%%html
<marquee style='widht: 34; color:red'>Hi, Welcome to the Mnist dataset Deep Learning</marquee>

In [2]:
# Simple Linear Regression using tensorflow V2
import tensorflow as tf

mnist=tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

predictions = model(x_train[:1]).numpy()
print(predictions)

done


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [6]:
predictions = model(x_train[:1]).numpy()
print(predictions)
print(tf.__version__)

[[ 0.45605257  0.42735064  0.36748955 -0.14354952 -0.45983952  0.14559379
  -0.60688454  0.9265168  -0.10235201  0.24655318]]
2.1.0


In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.12660569, 0.12302352, 0.11587528, 0.06951033, 0.05066247,
        0.09281597, 0.04373464, 0.20266242, 0.07243378, 0.10267597]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

2.3771367

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 17s 276us/sample - loss: 0.3023 - accuracy: 0.9123
Epoch 2/5
60000/60000 [==============================] - 13s 223us/sample - loss: 0.1474 - accuracy: 0.9561
Epoch 3/5
60000/60000 [==============================] - 14s 236us/sample - loss: 0.1100 - accuracy: 0.9673
Epoch 4/5
60000/60000 [==============================] - 13s 221us/sample - loss: 0.0899 - accuracy: 0.9720
Epoch 5/5
60000/60000 [==============================] - 13s 218us/sample - loss: 0.0768 - accuracy: 0.9765


In [12]:
model.evaluate(x_test,  y_test, verbose=2)

10000/10000 - 1s - loss: 0.0714 - accuracy: 0.9784


[0.07143896758882329, 0.9784]

In [13]:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])

In [14]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.0419532e-06, 2.4151651e-08, 7.4009281e-06, 9.9980207e-05,
        2.1793731e-09, 1.6557796e-06, 8.2336731e-13, 9.9985945e-01,
        9.1894105e-07, 2.6514133e-05],
       [1.9149915e-08, 1.5640085e-06, 9.9996758e-01, 2.9915343e-05,
        4.3966089e-14, 8.0986854e-07, 3.0087939e-08, 4.2272238e-15,
        8.0821387e-08, 2.6037039e-13],
       [1.8571404e-07, 9.9761873e-01, 1.4223740e-04, 1.2932515e-05,
        1.3716720e-04, 3.2890945e-05, 2.4134246e-05, 1.8393578e-03,
        1.9118297e-04, 1.1236216e-06],
       [9.9989653e-01, 1.0969878e-09, 8.0635891e-06, 3.0430010e-07,
        3.2970363e-06, 1.4926194e-05, 3.9106162e-05, 2.3260363e-05,
        2.7735945e-09, 1.4425454e-05],
       [4.7011767e-07, 1.3453036e-09, 1.1263585e-06, 4.2269935e-08,
        9.9837923e-01, 1.5267036e-06, 2.5437089e-06, 9.8383192e-05,
        1.9636793e-06, 1.5147087e-03]], dtype=float32)>